#!/usr/bin/env bash

FICHIER="autre_test.txt"
# Obligatoire de se rendre dans le répertoire d'écriture / lecture
cd /Users/pablo/Desktop/Developpement/bash/Z_fichiers_pr_test

: <<-"LECTURE"
exec 3<"$FICHIER" # ouvre le fichier pr lecture uniquement
OLDIFS="$IFS"
IFS=
while read -r -u 3 LIGNE || [ -n "$LIGNE" ] # lecture de la première ligne
# read -r : permet au slash de se comporter sans pouvoir spécial
# read -u : lit depuis le file descriptor qui suit
do
    echo "$LIGNE" # affichage de la ligne lue
done
IFS="$OLDIFS"
exec 3>&- # fermer le file descriptor 3
LECTURE

: <<-"LECTURE"
exec 3<"$FICHIER" # ouvre le file descriptor 3 pr lecture
grep $ <&3 # lit toutes les lignes du fichier
exec 3>&- # fermer le file descriptor 3
LECTURE

: <<-"LECTURE"
exec 3<>"$FICHIER" # ouvre le file descriptor 3 pr lecture et écriture
COMPTEUR=1
OLDIFS="$IFS"
IFS=
while read -r -u 3 LIGNE || [ -n "$LIGNE" ] # lecture de la première ligne
# read -r : permet au slash de se comporter sans pouvoir spécial
# read -u : lit depuis le file descriptor qui suit
do
    echo "$LIGNE" # affichage de la ligne lue
done
IFS="$OLDIFS"
exec 3>&- # fermer le file descriptor 3
LECTURE

: <<-"ECRITURE"
exec 3>"$FICHIER" # ouvre le file descriptor 3 pr écriture uniquement
# Si cette étape (ci-dessous) est pas faite, cela remplace le octet mais n'efface pas tous le contenu initial.
echo -n "" >"$FICHIER" # efface le contenu du fichier
# Redirige STDOUT et STDERR vers le file descriptor 3
echo "ABC" >&3
echo "DEF" >&3
exec 3>&- # fermer le file descriptor 3
ECRITURE

: <<-"ECRITURE"
exec 3<>"$FICHIER" # ouvre le file descriptor 3 pr lecture et écriture
# Si cette étape (ci-dessous) est pas faite, cela remplace le octet mais n'efface pas tous le contenu initial.
echo -n "" >"$FICHIER" # efface le contenu du fichier
# Redirige STDOUT et STDERR vers le file descriptor 3
echo "123" >&3
echo "456" >&3
exec 3>&- # fermer le file descriptor 3
ECRITURE
