#!/usr/bin/env bash
#
# Voici le document en ligne
#
# ce script permet de rechercher toutes les lignes qui matchent
# le contenu de $1 transmis en argumnent à la commande qui run le fichier
grep $1 <<EOF
mike x.123
joe x.234
sue x.555
pete x.818
sara x.822
bill x.919
EOF