#!/usr/bin/env bash
find / -type d -name bash -print 2>/dev/null
# les types sont :
#   b       block special
#   c       character special
#   d       directory
#   f       regular file
#   l       symbolic link
#   p       FIFO
#   s       socket