#!/usr/bin/env bash

# $1 : le path depuis lequel find effectue la recherche.

# Description du script :
# Obtention du fichier/répertoire le plus profond d'un path
# Ainsi que de son niveau absolu et relatif par rapport au répertoire/fichier de recherche
# Affichage du résumé à la fin.

# Contrôle des arguments 
SYNTAXE="\nSyntaxe :\n\t$(basename $0)    FICHIER_OU_REPERTOIRE_DE_RECHERCHE\n"
if [ -z "$1" ]
then
    echo -e "\nERREUR : aucun argument fourni."
    echo -e "$SYNTAXE"
    exit 1
else
    REPERTOIRE_RECHERCHE="$1"
    if [[ -d "$REPERTOIRE_RECHERCHE" ||  -f "$REPERTOIRE_RECHERCHE" ]]
    then
        : # ok
    else
        echo -e "\nERREUR : l'argument fourni \"$REPERTOIRE_RECHERCHE\" n'est pas un fichier/répertoire."
        echo -e "$SYNTAXE"
        exit 1
    fi
fi

# Obtention du nombre de niveau absolu
CHAR_SEPARATEUR_REPERTOIRE='/' # à adapter selon l'environnement = le char qui sépare les répertoires
NIVEAU_INITIAL="$( echo "$REPERTOIRE_RECHERCHE" | awk -F "$CHAR_SEPARATEUR_REPERTOIRE" ' { print NF } ' ) "
NIVEAU_MAX_ABSOLU=$NIVEAU_INITIAL
NIVEAU_MAX_ABSOLU_COURANT=$NIVEAU_MAX_ABSOLU
PATH_NIVEAU_MAX="$REPERTOIRE_RECHERCHE"
NIVEAU_MAX_RELATIF=0 # Besoin pr boucler sur les niveaux
NIVEAU_MAX_RELATIF_COURANT=0
# Si le tableau contient au moins un élément

# Principe de la boucle : du moment où au moins un fichier a été trouvé à un niveau, on essaie d'aller plus loin.
FLAG_NIVEAU_SUIVANT="true"
while [ $FLAG_NIVEAU_SUIVANT = "true" ]
do
    FLAG_NIVEAU_SUIVANT="false"
    while read FICHIER_OU_REPERTOIRE
    do
        PATH_NIVEAU_MAX=$FICHIER_OU_REPERTOIRE
        NIVEAU_MAX_RELATIF=$NIVEAU_MAX_RELATIF_COURANT
        ((NIVEAU_MAX_RELATIF_COURANT++))
        # Mis à true que si au moins un match
        FLAG_NIVEAU_SUIVANT="true"
        break
    # Le niveau relatif s'adapte à chaque fois pour les recherche suivante afin de limiter les recherches au strict minimum.
    done < <(find -s "$REPERTOIRE_RECHERCHE" -mindepth $NIVEAU_MAX_RELATIF_COURANT -print0 -quit | tr '\0' '\n')
done

echo "$NIVEAU_MAX_RELATIF"
echo "$PATH_NIVEAU_MAX"
NIVEAU_MAX_ABSOLU="$( echo "$PATH_NIVEAU_MAX" | awk -F "$CHAR_SEPARATEUR_REPERTOIRE" ' { print NF } ' ) "
echo "$NIVEAU_MAX_ABSOLU"

# Gestion du singulier/pluriel dans le message affiché
ACCORD_ABSOLU=""
if [ $((NIVEAU_MAX_ABSOLU)) -gt 1 ]
then
    ACCORD_ABSOLU="x"
else
    :
fi
ACCORD_RELATIF=""
if [ $((NIVEAU_MAX_RELATIF)) -gt 1 ]
then
    ACCORD_RELATIF="x"
else
    :
fi

echo -e "\nRésultats de la recherche :"
echo -e "Les recherches à partir du path \"$REPERTOIRE_RECHERCHE\" indiquent que le path le plus profond :"
echo -e "- possède $((NIVEAU_MAX_ABSOLU)) niveau${ACCORD_ABSOLU} en absolu."
echo -e "- possède $((NIVEAU_MAX_RELATIF)) niveau${ACCORD_RELATIF} en relatif au path de recherche)."
echo -e "- est : \"$PATH_NIVEAU_MAX\".\n"
