#!/usr/bin/env bash

FICHIER_A_REFORMATTER="/Users/pablo/Desktop/Developpement/bash/Z_fichiers_pr_test/travail_sur_le_texte"
ALIGNEMENT_DU_DEUXIEME_BLOC=25
STRING_ESPACE=""
OLDIFS=$IFS
IFS=
while read LIGNE
do
    # Remise à nul de l'espacement
    STRING_ESPACE=""
    # Remplacement des slash '/' par des antislash-slash '\/' pr permettre à sed son bon fonctionnement
    LIGNE="$(echo "$LIGNE" | sed -e 's/\//\\\//' )"
    # sed ici remplace les slash par des antislash sinon ils embêtent la commande sed qui sépare ses blocs par des '/'
    PREMIERE_PARTIE_LIGNE="$(echo "$LIGNE" | awk ' { print $1 } ' )" # | sed -e 's/\//\\\//' )"
    LONGUEUR_PREMIERE_PARTIE=${#PREMIERE_PARTIE_LIGNE}
    NB_ESPACE_REQUIS=$((ALIGNEMENT_DU_DEUXIEME_BLOC-LONGUEUR_PREMIERE_PARTIE))
    for ((i=0; i<$NB_ESPACE_REQUIS; i++))
    do
        STRING_ESPACE="$STRING_ESPACE "
    done
    DEUXIEME_PARTIE_LIGNE="$(echo "$LIGNE" | awk ' { for (i=2; i<=NF; i++) { printf ("%s ", $i) } } ' )" # | sed -e 's/\//\\\//' )"
    sed -i '' "s/$LIGNE/${PREMIERE_PARTIE_LIGNE}${STRING_ESPACE}\t${DEUXIEME_PARTIE_LIGNE}/" "$FICHIER_A_REFORMATTER"
    # sed -i '' : pas de fichier de back-up lors du remplacement

done < <(cat "$FICHIER_A_REFORMATTER")
IFS=$OLDIFS



