#!/usr/bin/env bash
# cookbook filename: embedded_documentation

echo 'Saisir le code du script au-dessus du : <<HEREDOCUMENT'

# Usage d'un ":" = ne rien faire, suivi d'un heredocument pour y mettre la documentation au format "Plain Old Documentation" ou format texte normal.
exit 0 # pour éviter le gaspillage des ressources de bash
: <<'FIN_DE_LA_DOCUMENTATION'

Embedded documentation such as Perl's Plain Old Documentation (POD),
or even plain text here.

Any accurate documentation is better than none at all.

Sample documentation in Perl's Plain Old Documentation (POD) format adapted from
CODE/ch07/Ch07.001_Best_Ex7.1 and 7.2 in the Perl Best Practices example tarball
"PBP_code.tar.gz".

=head1 NAME

MY~PROGRAM--One-line description here

=head1 SYNOPSIS

  MY~PROGRAM [OPTIONS] <file>

=head1 OPTIONS

  -h = This usage.
  -v = Be verbose.
  -V = Show version, copyright, and license information.


=head1 DESCRIPTION

A full description of the application and its features.
May include numerous subsections (i.e., =head2, =head3, etc.)

[...]


=head1 LICENSE AND COPYRIGHT

=cut

FIN_DE_LA_DOCUMENTATION
