#!/usr/bin/env bash

STRICT_ISO_8601='%Y-%m-%dT%H:%M:%S%z'
ISO_8601='%Y-%m-%d %H:%M:%S %Z'
ISO_8601_1='%Y-%m-%d %T %Z'
DATE_FICHIER='%Y%m%d%H%M%S'


#date "+Je peux écrire ce que j'aime : $ISO_8601"

# Affichage date avec fonction strftime utilisée via gawk
#gawk "BEGIN { print strftime(\"$ISO_8601\")}"

# Affichage du 1er octobre 2005
#gdate -d "2005-10-01" "+$ISO_8601_1"

gdate --resolution

