#!/usr/bin/env bash
let "var1 = 6" "var2 = 2" "var3=var1+var2"
echo $var3
let "var1 = 6" "var2 = 2" "var3=var1-var2"
echo $var3
let "var1 = 6" "var2 = 2" "var3=var1*var2"
echo $var3
let "var1 = 6" "var2 = 2" "var3=var1/var2"
echo $var3
let "var1 = 6" "var2 = 2" "var3=var1%var2"
echo $var3