#!/usr/bin/env bash
for ((i=0; i<10; i++))
do
    #echo "Boucle $i"
    :
done
echo ""

for ((i=0, j=0; i+j<20; i++, j++))
do
    #echo "Boucle i: $i j: $j"
	#echo "Résultat $((i*j))"
    :
done

SOMME=0
for VALUE in $(seq 1.0 0.01 1.1)
do
    #echo "Traitement de $VALUE"
    #$(echo "$SOMME+=$VALUE" | bc)
    CALCUL="2.5*3" # stockage du calcul dans un string
    echo $CALCUL | bc # affichage du résultat
    RESULTAT="$(echo "2.5*3" | bc)" # stockage du résultat dans un string pour affichage
    echo "Le résultat de $CALCUL est $RESULTAT"
    #echo "La somme de $SOMME et $VALUE donne "
    #SOMME=$NOUVELLE_SOMME
    #echo "$nb"
    awk 'BEGIN {printf "%.4f\n", 2.5*3}'
done
    



