#!/usr/bin/env bash

source fonctions_personnelles

# Syntaxe
SYNTAXE="$(syntaxe_afficher_si_erreur "$(basename $0)" "-a" "-b ARG_B")"

#
aflag=
bflag=

# since we don't want getopts to generate error
# messages, but want this script to issue its
# own messages, we will put, in the option list, a
# leading ':' to silence getopts.
while getopts :ab:h OPTION
do
    case $OPTION in
        a)  aflag=1
            ;;
        b)  bflag=1
            bval="$OPTARG"
            ;;
        h)  printf "%b\n" "$SYNTAXE"
            exit 0
            ;;
        \:) printf "\nERREUR : Argument manquant pour l'option -%s \n" $OPTARG # les ':'' signifie que la valeur de l'argument n'a pas été trouvée = argument manquant
            printf "%b\n" "$SYNTAXE"
            exit 2
            ;;
        \?) printf "ERREUR : Option inconnue : -%s\n" "$OPTARG"
            printf "%b\n" "$SYNTAXE"
            exit 2
            ;;
        esac >&2
done
shift $(($OPTIND - 1))

if [ "$aflag" ]
then
    printf "Option -a spécifiée\n"
else
    printf "\nERREUR : option -a non spécifiée.\n"
    printf "%b\n" "$SYNTAXE"
    exit 1
fi
if [ "$bflag" ]
then
    printf 'Option -b "%s" spécifiée\n' "$bval"
else
    printf "\nERREUR : option -b non spécifiée.\n"
    printf "%b\n" "$SYNTAXE"
    exit 1
fi
printf "\nLes arguments restant sont :\n%s\n" "$*"
