#!/usr/bin/env bash

FICHIERTAR='/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/testtar.tar'

tar -tf $FICHIERTAR |
# tar -t : liste les archives sur STDOUT
# tar -f : lit (ou écrit mais ici, lit) depuis le fichier
awk -F / '{ print $1 }' | 
# awk -F : field separator = '/'
# affiche du premier mot (selon séparateur) de chaque ligne donc répertoire de base du fichier
sort -u
# sort -u : suppression des doublons et tri (et sort les trie par ordre alphabétique)